Capstone-Design-2025-KGU/Carely_BE

- src/main/java/univ/kgu/carely/config/SwaggerConfig.java
> setting : Swagger 설정 완료

- src/main/java/univ/kgu/carely/domain/member/entity/Member.java
+ builder 패턴 적용시 isVerified에 default 값이 적용되지 않던 버그 수정
> fix : isVerified 가 false로 들어가지 않던 버그 수정

- build.gradle
- src/main/java/univ/kgu/carely/config/WebSocketConfig.java
- src/main/java/univ/kgu/carely/config/websocket/WebSocketConfig.java
- src/main/java/univ/kgu/carely/config/websocket/WebSocketEventListener.java
- src/main/java/univ/kgu/carely/domain/chat/controller/ChatController.java
- src/main/java/univ/kgu/carely/domain/chat/entity/ChatMessage.java
- src/main/java/univ/kgu/carely/domain/chat/entity/MessageType.java
#11
- Created ChatMessage entity
- Created chat controller
- Created event listener to handle client disconnection
- Created method to send messages
- Created method to establish client connection to WebSocket
- Created method to broadcast member status when session is disconnected
- Added WebSocket dependency
- Created WebSocket configuration file
> [FEAT] WebSocket Config & Create Chat Controller

- src/main/java/univ/kgu/carely/config/SwaggerConfig.java
- src/main/java/univ/kgu/carely/domain/member/dto/CustomUserDetails.java
- src/main/java/univ/kgu/carely/domain/member/repository/CustomMemberRepository.java
- src/main/java/univ/kgu/carely/domain/member/repository/MemberRepositoryImpl.java
- src/main/java/univ/kgu/carely/domain/member/service/MemberService.java
> [Feat] Swagger 설정

- src/main/java/univ/kgu/carely/domain/member/controller/MemberController.java
- src/main/java/univ/kgu/carely/domain/member/dto/request/ReqUpdateSkillDTO.java
- src/main/java/univ/kgu/carely/domain/member/dto/response/ResMemberPublicInfoDTO.java
- src/main/java/univ/kgu/carely/domain/member/repository/MemberRepositoryImpl.java
- src/main/java/univ/kgu/carely/domain/member/service/MemberService.java
- src/main/java/univ/kgu/carely/domain/member/service/impl/MemberServiceImpl.java
> [FEAT] member refactor

- build.gradle
- src/main/java/univ/kgu/carely/domain/member/service/impl/MemberServiceImpl.java
> feat : 회원가입시 프로필 이미지 기본값 설정

- src/main/java/univ/kgu/carely/config/TestDataConfig.java
- src/main/java/univ/kgu/carely/domain/member/dto/response/ResMemberPublicInfoDTO.java
- src/main/java/univ/kgu/carely/domain/member/entity/Member.java
- src/main/java/univ/kgu/carely/domain/member/service/impl/MemberServiceImpl.java
> [FEAT] 기본 이미지 설정 기능 수정

- build.gradle
- src/main/java/univ/kgu/carely/config/TestDataConfig.java
- src/main/java/univ/kgu/carely/domain/chat/controller/ChatRestController.java
- src/main/java/univ/kgu/carely/domain/chat/controller/ChatWebSocketController.java
- src/main/java/univ/kgu/carely/domain/chat/dto/ChatRoomResponse.java
- src/main/java/univ/kgu/carely/domain/chat/entity/ChatMember.java
- src/main/java/univ/kgu/carely/domain/chat/repository/ChatMemberRepository.java
- src/main/java/univ/kgu/carely/domain/chat/repository/ChatMessageRepository.java
- src/main/java/univ/kgu/carely/domain/chat/service/ChatMessageService.java
- src/main/java/univ/kgu/carely/domain/chat/service/impl/ChatMessageServiceImpl.java
- src/main/java/univ/kgu/carely/domain/member/controller/MemberController.java
- src/main/java/univ/kgu/carely/domain/member/dto/request/ReqUpdateSkillDTO.java
- src/main/java/univ/kgu/carely/domain/member/dto/response/ResMemberPublicInfoDTO.java
- src/main/java/univ/kgu/carely/domain/member/entity/Member.java
- src/main/java/univ/kgu/carely/domain/member/repository/MemberRepositoryImpl.java
- src/main/java/univ/kgu/carely/domain/member/service/MemberService.java
- src/main/java/univ/kgu/carely/domain/member/service/impl/MemberServiceImpl.java
#11 
- Create API to fetch chat rooms
> [FEAT] Create API to fetch chat rooms

- src/main/java/univ/kgu/carely/config/SecurityConfig.java
- src/main/java/univ/kgu/carely/config/WebConfig.java
> [FEAT] CORS 설정 추가

- Jenkinsfile-nightly
- ci/Dockerfile-aws-cli
- src/main/java/univ/kgu/carely/CarelyApplication.java
갑작스럽게 젠킨스가 동작하지 않는 에러
- amazon-linux 패키지 다운로드를 yum이 아닌 alpine으로 수행
- Swagger URL error 해결
> [Fix] Fix Jenkins Pipeline

- src/main/java/univ/kgu/carely/CarelyApplication.java
- src/main/java/univ/kgu/carely/domain/member/controller/MemberController.java
- src/main/java/univ/kgu/carely/domain/member/dto/response/ResMemberPublicInfoDTO.java
- src/main/java/univ/kgu/carely/domain/member/repository/CustomMemberRepository.java
- src/main/java/univ/kgu/carely/domain/member/repository/MemberRepositoryImpl.java
- src/main/java/univ/kgu/carely/domain/member/service/MemberService.java
- src/main/java/univ/kgu/carely/domain/member/service/impl/MemberServiceImpl.java
> feat : 이웃 검색 API 이용시 이름으로 검색 가능하도록 기능 추가

- src/main/java/univ/kgu/carely/config/SecurityConfig.java
- src/main/java/univ/kgu/carely/config/SwaggerConfig.java
- src/main/java/univ/kgu/carely/jwt/LoginFilter.java
- src/main/java/univ/kgu/carely/jwt/dto/LoginDTO.java
> [FEAT] 로그인 변경

- src/main/java/univ/kgu/carely/domain/member/controller/MemberController.java
- src/main/java/univ/kgu/carely/domain/member/dto/CustomUserDetails.java
- src/main/java/univ/kgu/carely/domain/member/service/MemberService.java
- src/main/java/univ/kgu/carely/domain/member/service/impl/MemberServiceImpl.java
- src/main/java/univ/kgu/carely/domain/team/controller/CommentController.java
- src/main/java/univ/kgu/carely/domain/team/controller/PostController.java
- src/main/java/univ/kgu/carely/domain/team/controller/TeamController.java
- src/main/java/univ/kgu/carely/domain/team/service/CommentService.java
- src/main/java/univ/kgu/carely/domain/team/service/PostService.java
- src/main/java/univ/kgu/carely/domain/team/service/TeamService.java
- src/main/java/univ/kgu/carely/domain/team/service/impl/CommentServiceImpl.java
- src/main/java/univ/kgu/carely/domain/team/service/impl/PostServiceImpl.java
- src/main/java/univ/kgu/carely/domain/team/service/impl/TeamServiceImpl.java
> [REFACTOR] 인증 정보 받는 방식 수정

- src/main/java/univ/kgu/carely/domain/meet/dto/response/ResMeetingDTO.java
- src/main/java/univ/kgu/carely/domain/meet/service/impl/MeetingServiceImpl.java
> [FIX] 수락된 약속이나 완료된 약속의 경우 상세주소를 같이 리턴하도록 수정

- src/main/java/univ/kgu/carely/domain/member/repository/impl/MemberRepositoryImpl.java
> [FIX] 개인정보 API 버그 수정

- src/main/java/univ/kgu/carely/domain/member/repository/impl/MemberRepositoryImpl.java
> [FIX] 다회 로그인이 발생하는 버그 수정

- src/main/java/univ/kgu/carely/domain/chat/dto/ChatMessageRequest.java
- src/main/java/univ/kgu/carely/domain/chat/dto/ChatMessageResponse.java
- src/main/java/univ/kgu/carely/domain/chat/entity/ChatMessage.java
- src/main/java/univ/kgu/carely/domain/chat/service/impl/ChatMessageServiceImpl.java
메세지를 통해 일부 Meeting 정보를 렌더링 할 수 없음
미팅 정보 일부 데이터를 Message 에서 가지고 있도록 함.
> [FEAT] Add date,time,chore to message entity

- build.gradle
- docker-compose.yaml
> [SETTING] docker compose support 추가 및 docker-compose 파일 수정

- src/main/java/univ/kgu/carely/domain/member/dto/response/ResMemberPrivateInfoDTO.java
- src/main/java/univ/kgu/carely/domain/member/dto/response/ResMemberPublicInfoDTO.java
- src/main/java/univ/kgu/carely/domain/member/repository/impl/MemberRepositoryImpl.java
- src/main/java/univ/kgu/carely/domain/member/service/impl/MemberServiceImpl.java
- src/main/java/univ/kgu/carely/domain/member/util/MemberMapper.java
> [FEAT] 나이 계산하여 반환하도록 수정

- src/main/java/univ/kgu/carely/domain/member/repository/impl/MemberRepositoryImpl.java
- src/main/java/univ/kgu/carely/util/UnitTrans.java
프론트엔드에서 이용할 떄 따로 가공하여 사용할 필요 없도록 단위를 변환하여 보내도록 수정했습니다.
> [FEAT] 반환하는 단위 수정

- src/main/java/univ/kgu/carely/domain/meet/dto/response/ResMemoryCardDTO.java
- src/main/java/univ/kgu/carely/domain/meet/repository/memory/impl/MemoryRepositoryImpl.java
- src/main/java/univ/kgu/carely/domain/meet/service/impl/MemoryServiceImpl.java
> [FEAT] 메모리 카드 반환값 추가

- src/main/java/univ/kgu/carely/domain/meet/dto/response/ResMeetingSmallInfoDTO.java
- src/main/java/univ/kgu/carely/dummy/MemberDummy.java
- src/main/java/univ/kgu/carely/dummy/MemoDummy.java
- src/main/java/univ/kgu/carely/dummy/MemoryDummy.java
- src/main/java/univ/kgu/carely/jwt/JwtUtil.java
- src/main/java/univ/kgu/carely/jwt/LoginFilter.java
- src/main/resources/application.yml
토큰과 데이터 자잘한 수정입니다
- 더미 데이터 작성 방식 개선
- 토큰 만료 시간 재조정
- 토큰 만료시 로그 출력
> [CHORE] refactor dummy data & add log for token

- src/main/java/univ/kgu/carely/domain/member/dto/response/ResMemberMapDTO.java
- src/main/java/univ/kgu/carely/domain/member/repository/CustomMemberRepository.java
- src/main/java/univ/kgu/carely/domain/member/repository/impl/MemberRepositoryImpl.java
- src/main/java/univ/kgu/carely/domain/member/service/impl/MemberServiceImpl.java
- src/test/java/univ/kgu/carely/domain/member/repository/impl/MemberRepositoryImplTest.java
> [FEAT] 이웃 검색시 응답 데이터 추가

- k8s/be.yaml
- src/main/java/univ/kgu/carely/domain/meet/dto/request/ReqMemoSumCreateDTO.java
- src/main/java/univ/kgu/carely/domain/meet/entity/Meeting.java
- src/main/java/univ/kgu/carely/domain/meet/service/impl/MeetingServiceImpl.java
- src/main/java/univ/kgu/carely/domain/meet/service/impl/MemoServiceImpl.java
- src/main/java/univ/kgu/carely/domain/meet/service/impl/MemoSumServiceImpl.java
- src/test/java/univ/kgu/carely/domain/meet/service/impl/MemoSumServiceImplTest.java
> [FIX] ai와의 api 연동 오류 수정

- src/main/java/univ/kgu/carely/domain/team/controller/TeamController.java
- src/main/java/univ/kgu/carely/domain/team/repository/team/CustomTeamRepository.java
- src/main/java/univ/kgu/carely/domain/team/repository/team/impl/TeamRepositoryImpl.java
- src/main/java/univ/kgu/carely/domain/team/service/TeamService.java
- src/main/java/univ/kgu/carely/domain/team/service/impl/TeamServiceImpl.java
- src/test/java/univ/kgu/carely/domain/team/repository/team/impl/TeamRepositoryImplTest.java
> feat : 본인 소속 그룹 찾기 기능 추가

- k8s/be.yaml
- src/main/java/univ/kgu/carely/domain/meet/dto/request/ReqMemoSumCreateDTO.java
- src/main/java/univ/kgu/carely/domain/meet/service/impl/MeetingServiceImpl.java
- src/main/java/univ/kgu/carely/domain/meet/service/impl/MemoServiceImpl.java
- src/main/java/univ/kgu/carely/domain/meet/service/impl/MemoSumServiceImpl.java
- src/test/java/univ/kgu/carely/domain/meet/service/impl/MemoSumServiceImplTest.java
> [SETTING] docker version up
